# Generated by Django 5.2.4 on 2025-11-29 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_candidate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='symbol',
        ),
    ]
