# Generated by Django 5.2.4 on 2025-11-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        ('users', '0005_remove_party_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='elections',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='elections.election'),
        ),
    ]
