# Generated by Django 5.2.4 on 2025-11-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_candidate_elections'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
