# Generated by Django 6.0 on 2025-12-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_voter_is_verified_voter_verification_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voter",
            name="has_voted",
        ),
    ]
