# Generated by Django 6.0 on 2025-12-18 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
        ("users", "0011_remove_voter_has_voted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_votes",
                to="users.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="election",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_votes",
                to="elections.election",
            ),
        ),
    ]
