# Generated by Django 6.0 on 2025-12-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_vote_candidate_alter_vote_election"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voter",
            old_name="mobile",
            new_name="mobile_no",
        ),
    ]
