# Generated by Django 6.0 on 2025-12-21 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
        ("users", "0014_campaign"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="manifesto",
            new_name="message",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="party_name",
        ),
        migrations.AddField(
            model_name="campaign",
            name="election",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elections.election",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campaign",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.candidate"
            ),
        ),
    ]
