# Generated by Django 6.0 on 2025-12-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_votervote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("voter", "Voter"),
                    ("candidate", "Candidate"),
                ],
                default="voter",
                max_length=20,
            ),
        ),
    ]
