# Generated by Django 6.0 on 2025-12-28 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0003_alter_election_results_published"),
        ("users", "0017_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.RenameField(
            model_name="vote",
            old_name="date",
            new_name="voted_on",
        ),
        migrations.RemoveField(
            model_name="voter",
            name="is_verified",
        ),
        migrations.AlterField(
            model_name="candidate",
            name="age",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="party",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="vote",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.candidate"
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="election",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_votes",
                to="elections.election",
            ),
        ),
        migrations.DeleteModel(
            name="VoterVote",
        ),
    ]
