# Generated by Django 5.2.4 on 2025-12-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_customuser_options_rename_date_vote_voted_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
